name: Build Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NPM_TOKEN: ""

jobs:
  run-tests:
    name: Run Build Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: ./.yarn/yarn.cjs install --immutable --mode=skip-build
      - name: Validating syntax
        run: ./.yarn/yarn.cjs test:tsc
      - name: Linting
        run: ./.yarn/yarn.cjs test:lint
      - name: Validating formatting
        run: ./.yarn/yarn.cjs test:fmt
      - name: Attempt Build
        run: ./.yarn/yarn.cjs build
